version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smart-attendance-db
    environment:
      POSTGRES_DB: smart_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    image: redis:7-alpine
    container_name: smart-attendance-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: smart-attendance-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/smart_attendance
      REDIS_URL: redis://cache:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 5000
      NODE_ENV: production
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - "5000:5000"
    depends_on:
      - db
      - cache
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-attendance-client
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
